spring:
  output:
    ansi:
      enabled : always

  h2:
    console:
      enabled: true
      path: /h2-console

  session:
    timeout: 86400

  datasource:
    url: jdbc:h2:mem:planetland2;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

  servlet:
    multipart:
      max-file-size: 10MB

server:
  servlet:
    session:
      cookie:
        max-age: 172800
