spring:
  output:
    ansi:
      enabled : always

  h2:
    console:
      enabled: true
      path: /h2-console

  ## 페이징 처리할 때 1부터 시작하게
  data:
    web:
      pageable:
        one-indexed-parameters: true

  datasource:
    url: jdbc:h2:mem:zunlog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
